apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-filestore-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.134
    path: /airflow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-filestore-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
