apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  selector:
    app: spark-master
  ports:
    - name: spark
      port: 7077
      targetPort: 7077
    - name: webui
      port: 8080
      targetPort: 8080
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: spark-master
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: spark-master
#   template:
#     metadata:
#       labels:
#         app: spark-master
#     spec:
#       containers:
#       - name: spark-master
#         image: apache/spark:3.5.3
#         command:
#           - /opt/spark/sbin/start-master.sh
#         ports:
#           - containerPort: 7077
#           - containerPort: 8080

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-master
spec:
  serviceName: spark-master
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: stehedor/spark-custom:latest
        # image: apache/spark:3.5.3
        command:
          - /bin/bash
          - -c
          - |
            /opt/spark/sbin/start-master.sh && \
            tail -f /opt/spark/logs/*
        # command:
        #   - /opt/spark/bin/spark-class
        #   - org.apache.spark.deploy.master.Master
        env:
          - name: SPARK_USER
            value: "airflow"
          - name: HADOOP_USER_NAME
            value: "airflow"
          - name: USER
            value: "airflow"
          # 
          - name: SPARK_MASTER_HOST
            value: "0.0.0.0"
            # value: spark-master
          - name: SPARK_MASTER_PORT
            value: "7077"
          - name: SPARK_MASTER_WEBUI_PORT
            value: "8080"
        ports:
          - containerPort: 7077
          - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      securityContext:
          runAsUser: 50000    # Obliga a correr como usuario 50000 (Airflow)
          runAsGroup: 0       # Opcional: Grupo root (común en Bitnami/Apache)
          fsGroup: 0
      containers:
      - name: spark-worker
        image: stehedor/spark-custom:latest
        # image: apache/spark:3.5.3
        command:
          - /opt/spark/bin/spark-class
          - org.apache.spark.deploy.worker.Worker
          - spark://spark-master:7077
        env:
          # --- AÑADE ESTAS VARIABLES PARA ARREGLAR EL LOGIN ---
          - name: SPARK_USER
            value: "airflow"
          - name: HADOOP_USER_NAME
            value: "airflow"
          - name: USER
            value: "airflow"
          # ----------------------------------------------------
          - name: SPARK_MASTER_PORT
            value: "7077"
          - name: SPARK_MASTER_WEBUI_PORT
            value: "8080"
        volumeMounts:
          - name: airflow-filestore
            mountPath: /opt/airflow
          # --- AÑADIDO: Montar espacio de trabajo temporal ---
          - name: spark-work-dir
            mountPath: /opt/spark/work
      volumes:
      - name: airflow-filestore
        persistentVolumeClaim:
          claimName: airflow-filestore-pvc
      # --- AÑADIDO: Definir volumen temporal ---
      - name: spark-work-dir
        emptyDir: {}
---