apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-env
data:
  AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
  # AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
  # AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@airflow-postgres/airflow
  AIRFLOW__CORE__FERNET_KEY: "LEMIyIaNoe0an_JkV5zAsTKEypRdvnEoppdRd7n6p5w="
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__API__AUTH_BACKEND: airflow.api.auth.backend.basic_auth
  AIRFLOW_HOME: /opt/airflow
  PROJECT_HOME: /opt/airflow
  AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs

  AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE: /opt/airflow/pod_template.yaml
  
  AIRFLOW__KUBERNETES__NAMESPACE: default
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: stehedor/airflow-custom
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: latest
  AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "true"
  AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_FAILURE: "true"