apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-local-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany      
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/tehe/Work/FBID/practica_prediccion-vuelos/practica_containers/30_k8s_mode/volume-local/airflow
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-filestore-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
